---
- hosts: nfs-ntdi07
  remote_user: root
  tasks:
   - name: copy ctrl-mnt to remote
     copy:
       src: ctrl-mnt.sh
       dest: /tmp/ctrl-mnt.sh
       owner: root
       group: root
       mode: 0744
   - name: umount nfs mount
     command: "/tmp/ctrl-mnt.sh off"
   - name: mount nfs mount
     command: "/tmp/ctrl-mnt.sh on"
